### PR TITLE
Await commit during a rebalance

### LINKED ISSUE #590: Many records duplicately processed after rebalancing
Originally reported on the zio-kafka discord by user `amszio`

> We are working on a new data processing application based on zio-kafka v2.0.1. Performance of the zio-kafka is amazing. However, we found a major issue during our testing phase. During rebalancing, zio-kafka is duplicating messages. Issue exists in v2.0.1, v2.0.2 and v2.0.3 (scala 2.13 and 3.2.1 have same issue). I saw https://github.com/zio/zio-kafka/issues/280 is fixed but looks like issue still exists. Anyone faces same or similar issue? Any help is appreciated.
> 
> To reproduce locally;
> * I've copied following code piece from zio-kafka homepage to be sure it's not due my business logic
> * Have a running kafka (docker-compose).
> * Input and output topics with min 2 partitions.
> * Send some data to input topic.
> * Start first zio-kafka app.
> * Start second zio-kafka app after first zio-kafka start consuming messages (this triggers rebalancing).
> * Wait until all messages are consumed by two apps.
> * Count messages in output_topic.
> 
> Note: When I start two applications at the same time and don't stop any of them till the end, this issue doesn't exist, both input and output topics have same amount of data.
> 
>     Consumer
>       .subscribeAnd(Subscription.topics("input_topic"))
>       .plainStream(Serde.byteArray, Serde.string)
>       .map { record =>
>         val producerRecord: ProducerRecord[Array[Byte], String] = new ProducerRecord("output_topic", record.record.value)
>         (producerRecord, record.offset)
>       }
>       .mapChunksZIO { chunk =>
>         val records = chunk.map(_._1)
>         val offsetBatch = OffsetBatch(chunk.map(_._2))
>         Console.printLine(s"Producing ${records.size} records") *>
>           ZIO.attemptBlocking(Thread.sleep(1000)) *> //Not to send tons of messages to reproduce the issue.
>           Producer.produceChunk[Any, Array[Byte], String](records, Serde.byteArray, Serde.string) *>
>           offsetBatch.commit.as(Chunk(()))
>       }
>       .runDrain

### PR DESCRIPTION
**Pull request by erikvanoosten**
Fixes #590 "Many records duplicately processed after rebalancing"

In this change we introduce a new mode that holds up a rebalance until all messages that were provided to the stream of a revoked partition, have been committed.

### Motivation

Here is a common (single partition) scenario around rebalances:

1. a consumer polls some messages and puts them in the streams (let's say messages with offsets 0 to 100)
1. asynchronously, the user processes these messages. Some of them are committed (let's say up to offset 50), the rest is still being processed when...
1. a rebalance happens, the partition is revoked and assigned to another consumer on another instance
1. the consumer continues to process the remaining messages with offsets 50 to 100, and tries to commit those offsets
1. _at the same time,_ another consumer on another instance, starts consuming from the last committed offset (which is 50) and will process the same messages with offsets 50 to 100

Messages with offsets 50 to 100 are being processed by both consumers simultaneously. Note that both consumers will try to commit these offsets. Until the first consumer is ready, the stored offsets can go up and down and are therefore unreliable.

After merging this change, the scenario will unfold as follows:

1. a consumer polls some messages and puts them in the streams (let's say messages with offsets 0 to 100). Zio-kafka keeps track of the highest provided offset
1. asynchronously, the user processes these messages. Some of them are committed (let's say up to offset 50), the rest is still being processed when...
1. a rebalance happens, the partition is revoked and assigned to another consumer on another instance
   * the consumer continues to process the remaining messages with offsets 50 to 100, and tries to commit those offsets
   * inside the onRevoked callback, zio-kafka continues to process commit commands from the user
   * zio-kafka continues to do so until the commit with the highest provided offset (offset 100) completes
   * the onRevoked callback completes, signalling to Kafka that the next consumer may start consuming from the partition
1. another consumer on another instance, starts consuming from the last committed offset (which is now 100, problem solved!)

### Commit queue

Because both the main runloop, and the rebalance listener need to process (and thus receive) commits commands, the commit commands were moved to a separate queue. Because the main runloop may still need to be kickstarted when it is no longer polling, a new command `CommitAvailable` was introduced.

### Complications

1. The chosen solution is not suitable for all consumers.
   - There are use cases where not all messages are read from the stream. For example, some want to read exactly 100 messages from a topic and then stop consuming. In that case the user has no intention to commit all messages, and therefore we should not wait for that to happen. Since stream consumers can basically do whatever they want, the only way we can support such use cases is by letting the consumer tell zio-kafka that they are done with committing. This requires an API change. For example, we can let the user tell zio-kafka that a given commit is the last one.
   - Not all consumers commit offsets (to Kafka) in the first place. In a future change we could make it work for commits to other stores though. As a workaround, these users can commit to both places.
   - Some users need access to the consumer from their stream. During a poll the consumer is in use and therefore not available for the stream. For some use cases the admin api, or a second consumer could function as a workaround.
1. It requires Kafka client 3.6.0. In earlier versions there was no way to wait for async commits to complete. (See [KAFKA-10337](https://issues.apache.org/jira/browse/KAFKA-10337).)

### Same thread executor

The Kafka client requires that any nested invocations (that is, from the rebalance listener callback) to the java consumer happens from the same thread. This is very much at odds with how ZIO works. Attempts to convince the Kafka committers to relax this requirement (with [KIP-944](https://cwiki.apache.org/confluence/x/chw0Dw)) failed; they could not be convinced that this is a problem. This is circumvented by using a special same-thread-runtime which runs on the thread of the caller. However, some operations such as `ZIO.timeout` and anything with `Schedules` will still shift work to another thread. We work around this by using blocking time and checking whether a `Promise` is done before awaiting it.

### Collateral

This change also:
- fixes order of `private` and `final`
- removes some completely useless tests

### Future

In the future [KIP-983](https://cwiki.apache.org/confluence/x/9Z6zDw) might become available. Once it is, we can dramatically simplify the implementation of this feature.

### Related

The same issue is present in:
- f2s-kafka: https://github.com/fd4s/fs2-kafka/issues/1200
- alpakka-kafka: https://github.com/akka/alpakka-kafka/issues/1038

In fact, every program that does polls and commits asynchronously is likely affected.

### Non-goals

This change does not try to solve the following goals. However, these can be addressed in future PRs.

- Awaiting commits after stopping the consumer, e.g. due to program shutdown (see #1087).
- Support consumers that want to commit only a portion of the given messages.
- Support transactional consumer/producer.
- Support external commits.

This branch is based on the work of abandoned PRs #788 and #830 and builds on preparatory work in PRs #744, #1068, #1073 #1086, #1089 and #1097.

### CODE REVIEW

**Comment by erikvanoosten** [comment]
@svroonland @guizmaii Perhaps we should offer this as an experimental feature at first. WDYT?

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 1]
```diff
@@ -22,24 +22,35 @@ import scala.jdk.CollectionConverters._
...
   offsetRetrieval: OffsetRetrieval,
   userRebalanceListener: RebalanceListener,
   restartStreamsOnRebalancing: Boolean,
+  rebalanceSafeCommits: Boolean,
   currentStateRef: Ref[State],
   committedOffsetsRef: Ref[CommitOffsets],
   fetchStrategy: FetchStrategy
 ) {
 
+  /**
```
Comment (svroonland) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:45]: Are there any other kafka consumer or kafka broker settings that limit the acceptable values here?

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 2]
```diff
@@ -128,19 +139,124 @@ private[consumer] final class Runloop private (
...
+        ZIO.logDebug(s"Async commit of ${offsets.size} offsets for ${commits.size} commits") *>
+          ZIO.attempt(consumer.commitAsync(offsets, callback)).catchAll(onFailure)
+      } else {
+        ZIO.unit
+      }
+
+    // Note, we cannot use ZStream.fromQueue because that will emit nothing when the queue is empty.
+    // Instead, we poll the queue in a loop.
+    ZStream
+      .fromZIO(blockingSleep(100.millis) *> commitQueue.takeAll)
```
Comment (svroonland) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:204]: Move it to some Runloop-private named constant or the ConsumerSettings

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 3]
```diff
@@ -174,7 +291,7 @@ private[consumer] final class Runloop private (
       new OffsetCommitCallback {
         override def onComplete(offsets: util.Map[TopicPartition, OffsetAndMetadata], exception: Exception): Unit =
           Unsafe.unsafe { implicit u =>
-            runtime.unsafe.run {
+            sameThreadRuntime.unsafe.run {
```
Comment (svroonland) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:294]: See comment below about user-land effects (which I wrote before noticing this bit): here as well a failed commit can result in executing a whole chain of ZIO effects while blocking the poll loop.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 4]
```diff
@@ -517,12 +638,12 @@ private[consumer] final class Runloop private (
...
           val rc = RebalanceConsumer.Live(c)
           ZIO
-            .attempt(c.subscribe(pattern.pattern, rebalanceListener.toKafka(runtime, rc)))
+            .attempt(c.subscribe(pattern.pattern, rebalanceListener.toKafka(sameThreadRuntime, rc)))
             .as(Chunk.empty)
         case SubscriptionState.Subscribed(_, Subscription.Topics(topics)) =>
           val rc = RebalanceConsumer.Live(c)
           ZIO
-            .attempt(c.subscribe(topics.asJava, rebalanceListener.toKafka(runtime, rc)))
+            .attempt(c.subscribe(topics.asJava, rebalanceListener.toKafka(sameThreadRuntime, rc)))
```
Comment (svroonland) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:646]: We should avoid running potential 'user-land' code on the same thread runtime, such as emitting diagnostics, which can result in a whole chain of ZIO effects being executed, while blocking the poll loop. We could explicitly fork the effects in the `emitDiagnostics` RebalanceListener or come up with some mechanism to make it explicit that we _don't_ want to fork the effects.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 5]
```diff
@@ -128,19 +139,124 @@ private[consumer] final class Runloop private (
...
+    //   - Get all commits from the commit queue.
+    //   - Start an async commit for these commits.
+    // - Collect all these new (pending) commits.
+    // - repeat the above until:
+    //   - All streams that were ended have completed their work.
+    //   - We have seen a completed or pending commit for all endOffsets.
+    //     The end-offsets are those offsets for which commits need to be completed for a stream to be done.
+    // - Do a single sync commit without any offsets, this has the side-effect of blocking until all
+    //   preceding async commits are complete (this requires kafka-client 3.6.0 or later).
+    // - Return the new commits so that they can be added to the runloop state.
```
Comment (svroonland) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:183]: Why should we do that, if they're no longer pending but completed (by the sync commit?) ?

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 6]
```diff
@@ -128,19 +139,124 @@ private[consumer] final class Runloop private (
...
+    // Note, we cannot use ZStream.fromQueue because that will emit nothing when the queue is empty.
+    // Instead, we poll the queue in a loop.
+    ZStream
+      .fromZIO(blockingSleep(100.millis) *> commitQueue.takeAll)
+      .tap(doAsyncCommits)
+      .forever
+      .takeWhile(_ => java.lang.System.nanoTime() <= deadline)
+      .scan(Chunk.empty[Runloop.Commit])(_ ++ _)
+      .takeUntilZIO { newCommits =>
+        for {
```
Comment (svroonland) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:210]: I would extract a method for the for comprehension

**Review by svroonland — COMMENTED** [review]
Nice! I don't see major issues besides that we need to carefully consider the same-thread behavior changes, a few comments/questions for now.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 5 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:183]: Because we're collecting commits that come in on the commit queue, including commits for partitions that are not ended.

Comment (svroonland) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:183]: But after the sync commit they are no longer pending, right? so why do we put them in the pendingCommits in the State..?

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 1 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:45]: I don't know. I am just guessing here. I will go through the Kafka configurations and see if this is configurable in the first place. It might be a server configuration.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 4 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:646]: Yes, that is good thinking.
Re. user written rebalance listener, I suppose we should remove that feature. Unfortunately it is needed for transaction at the moment.
Re. diagnostics, we could use forking indeed.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 5 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:183]: Ah, mmm. Yeah, that is a good point. 😄

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 1 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:45]: Found it. [scheduled.rebalance.max.delay.ms](https://kafka.apache.org/documentation/#connectconfigs_scheduled.rebalance.max.delay.ms) 

> The maximum delay that is scheduled in order to wait for the return of one or more departed workers before rebalancing and reassigning their connectors and tasks to the group. During this period the connectors and tasks of the departed workers remain unassigned
> Default: 300000 (5 minutes)

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:45]: Hmm maybe not. That is a Kafka connect config 😞

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 2 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Fixed in https://github.com/zio/zio-kafka/pull/1098/commits/a4fd6b5d42ad175754604d0e4642815de2ffc81c

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 6 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Fixed in https://github.com/zio/zio-kafka/pull/1098/commits/a4fd6b5d42ad175754604d0e4642815de2ffc81c

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 5 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Fixed in https://github.com/zio/zio-kafka/pull/1098/commits/a4fd6b5d42ad175754604d0e4642815de2ffc81c

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 1 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:45]: I cannot find a setting that could configure the timeout.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 3 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:298]: Addressed in https://github.com/zio/zio-kafka/pull/1102

File: zio-kafka/src/main/scala/zio/kafka/consumer/ConsumerSettings.scala [hunk 7]
```diff
@@ -154,6 +155,32 @@ final case class ConsumerSettings(
   def withRestartStreamOnRebalancing(value: Boolean): ConsumerSettings =
     copy(restartStreamOnRebalancing = value)
 
+  /**
+   * @param value
+   *   Whether to hold up a rebalance until all offsets of consumed messages have been committed. The default is
+   *   `false`, but the recommended value is `true` as it prevents duplicate messages.
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/ConsumerSettings.scala:161]: Why not `true` as the default then? 
Most people don't read documentation until something doesn't work as expected or until they experience an issue. 
I'd probably prefer to use the "safe" behaviour as the default one. 
People don't expect duplicate messages.

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/ConsumerSettings.scala:161]: Unfortunately `true` is not a safe default.
If you're not committing offsets, or not committing all offsets (e.g. you're using `take(100)` on the stream), enabling this feature will make rebalances very slow (they'll be blocked until the time out of 3 minutes).

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 8]
```diff
@@ -128,19 +144,123 @@ private[consumer] final class Runloop private (
...
+      .forever
+      .takeWhile(_ => java.lang.System.nanoTime() <= deadline)
+      .scan(Chunk.empty[Runloop.Commit])(_ ++ _)
+      .takeUntilZIO(endingStreamsCompletedAndCommitsExist)
+      .tap(_ => commitSync)
+      .runDrain
+      .ensuring {
+        ZIO.logDebug(s"Done waiting for ${streamsToEnd.size} streams to end")
+      }
+  }
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:248]: This code is only used in the rebalance mechanism so IMO it should go inside the `rebalanceListener` code block:
```scala
private val rebalanceListener: RebalanceListener = {
  
  ...
   
  // somewhere here
  
  ...
}
```

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopCommand.scala [hunk 9]
```diff
@@ -17,15 +16,12 @@ object RunloopCommand {
   /** Used as a signal that another poll is needed. */
   case object Poll extends Control
 
+  /** Used as a signal to the poll-loop that commits are available in the commit-queue. */
+  case object CommitAvailable extends Control
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopCommand.scala:20]: 🔴 This command is never handled in the code

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 10]
```diff
@@ -108,7 +124,7 @@ private[consumer] final class Runloop private (
           state          <- currentStateRef.get
           streamsToEnd = if (restartStreamsOnRebalancing && !rebalanceEvent.wasInvoked) state.assignedStreams
                          else state.assignedStreams.filter(control => revokedTps.contains(control.tp))
-          _ <- ZIO.foreachDiscard(streamsToEnd)(_.end)
+          _ <- endStreams(state, streamsToEnd, awaitStreamCommits = rebalanceSafeCommits)
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:127]: Why do we need to pass the `rebalanceSafeCommits` into the parameters of this function? 
This `endStreams` function already has access to the `rebalanceSafeCommits` variable

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopCommand.scala (hunk 9 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopCommand.scala:20]: The same is true for `Poll`. The only purpose of `Poll` and `CommitAvailable` is to kick start the runloop when it has halted.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 10 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:127]: Hmm, that may indeed no longer be needed, thanks. In the previous branch (the first working prototype) there was only a single method to end streams. In this branch I didn't try to converge them so now there are 2 (the other one being `endRevokedPartitions`). Anyways, this is where this parameter is coming from.

I'd like to investigate if we can converge the 2 stream ending methods in a future PR. For now we can remove the `awaitStreamCommits` parameter and move all this code inside the rebalance listener.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 11]
```diff
@@ -128,19 +144,123 @@ private[consumer] final class Runloop private (
...
+        ZIO.unit
+      }
+
+    def endingStreamsCompletedAndCommitsExist(newCommits: Chunk[Commit]): Task[Boolean] =
+      for {
+        streamResults <-
+          ZIO.foreach(streamsToEnd) { stream =>
+            for {
+              isDone    <- stream.completedPromise.isDone
+              endOffset <- if (isDone) stream.completedPromise.await else ZIO.none
```
[the remark this answers is not in the document]
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:209]: `PartitionStreamControl.end` puts an end token in the queue. The stream itself only ends once it has seen that end token. Perhaps we should rename the `end` method to something else to make this clearer. Suggestions welcome!

As for why this is all written this way: we need to be very careful because not all ZIO operations are allowed on the same-thread-runtime. If we abstract parts of this code, this constraint may no longer be visible. We could solve this with adding documentation (e.g. 'safe to use from same-thread-runtime'), but keeping stuff close together feels safer to me.

BTW, the same-thread-runtime really is quite annoying. For example, we cannot use `await` on a non-completed promise.

[the remark this answers is not in the document]
Comment (guizmaii) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:209]: > As for why this is all written this way: we need to be very careful because not all ZIO operations are allowed on the same-thread-runtime. If we abstract parts of this code, this constraint may no longer be visible.

Ok I get it. Indeed it's better this way! Thanks

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 12]
```diff
@@ -128,19 +144,123 @@ private[consumer] final class Runloop private (
...
+    //   preceding async commits are complete (this requires kafka-client 3.6.0 or later).
+    //   Because all commits created here (including those from non-ending streams) are now complete, we do not
+    //   have to add them to the pending commits of the runloop state.
+
+    val deadline = java.lang.System.nanoTime() + maxEndingStreamsInterval - commitTimeout.toNanos
+
+    val endingTps = streamsToEnd.map(_.tp).toSet
+    def commitsOfEndingStreams(commits: Chunk[Runloop.Commit]): Chunk[Runloop.Commit] =
+      commits.filter(commit => (commit.offsets.keySet intersect endingTps).nonEmpty)
+    val previousPendingCommits = commitsOfEndingStreams(state.pendingCommits)
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:192]: This `previousPendingCommits` value is always computed while it's not always used. It could be only computed when needed

Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:192]: This `previousPendingCommits` value is always computed while it can be unused.
Can't we only compute it when we need it?

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:192]: Sure! I'll make it a `def`.

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: It's a `lazy` val in https://github.com/zio/zio-kafka/pull/1098/commits/94375bc97ea51ec305978a28c10dda48b9143aeb

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 13]
```diff
@@ -128,19 +144,123 @@ private[consumer] final class Runloop private (
...
+          val allPendingCommits         = previousPendingCommits ++ commitsOfEndingStreams(newCommits)
+          endOffsets.forall { endOffset =>
+            val tp     = endOffset.topicPartition
+            val offset = endOffset.offset
+            committedOffsets.contains(tp, offset) ||
+            allPendingCommits.exists { pendingCommit =>
+              pendingCommit.offsets.get(tp).exists { pendingOffset =>
+                pendingOffset.offset() >= offset
+              }
+            }
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Could we make this piece of boolean logic easier to read with nicely named variables maybe?
Something like:
```scala
def offsetCommited = committedOffsets.contains(tp, offset)
// I didn't find a good name for this one
def `<aGoodName>` = allPendingCommits.exists { pendingCommit =>
              pendingCommit.offsets.get(tp).exists { pendingOffset =>
                pendingOffset.offset() >= offset
              }
            }

offsetCommited || `<aGoodName>`
```

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 14]
```diff
@@ -22,24 +22,40 @@ import scala.jdk.CollectionConverters._
...
+   * In this time zio-kafka awaits processing of records and the completion of commits.
+   *
+   * We use 3/5 of `maxPollInterval` which by default calculates to 3 minutes.
+   */
+  private val maxEndingStreamsInterval = (maxPollInterval.toNanos / 5L) * 3L
+
+  /**
+   * Time between polling the commit queue from the rebalance listener when `rebalanceSafeCommits` is enabled.
+   */
+  private val commitQueuePollInterval = 100.millis
```
[the remark this answers is not in the document]
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Addressed in https://github.com/zio/zio-kafka/pull/1098/commits/94375bc97ea51ec305978a28c10dda48b9143aeb.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 8 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Addressed in https://github.com/zio/zio-kafka/pull/1098/commits/94375bc97ea51ec305978a28c10dda48b9143aeb.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 13 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: If you want readability its going to be a long name 😄  I'll think about it.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 12 above)
Comment (guizmaii) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Why not moving it in the block of code using it?

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 15]
```diff
@@ -73,6 +75,127 @@ private[consumer] final class Runloop private (
...
+      // - Every `commitQueuePollInterval` until the deadline has been reached:
+      //   - Get all commits from the commit queue.
+      //   - Start an async commit for these commits.
+      // - Collect all these new (pending) commits.
+      // - repeat the above until:
+      //   - All streams that were ended have completed their work, and
+      //   - we have seen a completed or pending commit for all end-offsets.
+      //     An end-offset of a stream is the offset of the last record given to that stream.
+      // - Do a single sync commit without any offsets, this has the side-effect of blocking until all
+      //   preceding async commits are complete (this requires kafka-client 3.6.0 or later).
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:129]: To be sure to correctly understand this comment and the code, it seems to me (I could be wrong, ofc) that the `commitSync` will be repeated until one of the conditions is satisfied but it seems to me that, according to this comment, you're not expecting this `commitSync` call to be done more than once 🤔

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 16]
```diff
@@ -73,6 +75,127 @@ private[consumer] final class Runloop private (
...
+        .tap(commitAsync)
+        .forever
+        .takeWhile(_ => java.lang.System.nanoTime() <= deadline)
+        .scan(Chunk.empty[Runloop.Commit])(_ ++ _)
+        .takeUntilZIO(endingStreamsCompletedAndCommitsExist)
+        .tap(_ => commitSync)
+        .runDrain
+        .ensuring {
+          ZIO.logDebug(s"Done waiting for ${streamsToEnd.size} streams to end")
+        }
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:196]: Related to this remark: https://github.com/zio/zio-kafka/pull/1098/files#r1386974834
If you're expecting only 1 `commitSync` call, I'd write this code this way:
```scala
    ZStream
      .fromZIO(blockingSleep(commitQueuePollInterval) *> commitQueue.takeAll)
      .tap(commitAsync)
      .scan(Chunk.empty[Runloop.Commit])(_ ++ _)
      .takeUntilZIO(commits =>
        ZIO.succeed(java.lang.System.nanoTime() > deadline) || endingStreamsCompletedAndCommitsExist(commits)
      )
      .forever
      .runDrain *>
      commitSync *>
      ZIO.logDebug(s"Done waiting for ${streamsToEnd.size} streams to end")
```

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 12 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Because then it is recalculated every 100ms.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 13 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Addressed in https://github.com/zio/zio-kafka/pull/1098/commits/d1a961f4bf55832f56de178e6ca8b9b9104b7495:

```scala
val allStreamsCompleted = streamResults.forall(_._1)
allStreamsCompleted && {
  val endOffsets: Chunk[Offset] = streamResults.flatMap(_._2)
  val allPendingCommits         = previousPendingCommits ++ commitsOfEndingStreams(newCommits)
  endOffsets.forall { endOffset =>
    val tp                    = endOffset.topicPartition
    val offset                = endOffset.offset
    def endOffsetWasCommitted = committedOffsets.contains(tp, offset)
    def endOffsetCommitIsPending = allPendingCommits.exists { pendingCommit =>
      pendingCommit.offsets.get(tp).exists { pendingOffset =>
        pendingOffset.offset() >= offset
      }
    }
    endOffsetWasCommitted || endOffsetCommitIsPending
  }
}

```

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 16 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Your code is correct! It is like that now in:
https://github.com/zio/zio-kafka/pull/1098/commits/36225bca90ff5ffcea4a84e8c2cb2268bc6284c6

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 10 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: The parameter is gone in https://github.com/zio/zio-kafka/pull/1098/commits/d1a961f4bf55832f56de178e6ca8b9b9104b7495.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 15 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Fixed now.

**Comment by erikvanoosten** [comment]
> One thing I want to carefully review is off-by-one errors in the offsets.

This is now done and indeed there was a bug which is now fixed.

I have marked the new mode as experimental.

@guizmaii @svroonland When the test complete (in ~20 minutes), this PR is ready for merging.

**Comment by erikvanoosten** [comment]
Haha, I cheered too early. Working on it... 😄

**Comment by erikvanoosten** [comment]
> It seems we have a new flaky test:
> 
> ```
>     - Consumer Streaming - does not process messages twice for transactional producer, even when rebalancing - org.apache.kafka.clients.consumer.RangeAssignor
> Timeout of 2 m exceeded.
> ```

This has been fixed.

**Comment by erikvanoosten** [comment]
Okay, _now_ this PR is ready for merging. The tests have run several time without issues.

There is one outstanding comment (about configuration parameters) but I cannot answer that question (I did try). By marking this feature as experimental we can collect feedback about this (and other things) from the adventurous users and not disappoint the users that need more stability.

@svroonland @guizmaii Please review again.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 17]
```diff
@@ -73,6 +75,120 @@ private[consumer] final class Runloop private (
     commandQueue.offer(RunloopCommand.RemoveSubscription(subscription)).unit
 
   private val rebalanceListener: RebalanceListener = {
```
Comment (svroonland) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:77]: Maybe we should extract a class to a separate file here

Comment (svroonland) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:77]: Yeah, separate PR is fine

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 3 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:292]: Yes, you are entirely correct; #1102 solves the problem for diagnostics.
Besides diagnostics, do you see another way in which a failed commit results in a chain of ZIO effects?

Comment (svroonland) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:292]: With code like `offset.commit.catchAll(e => callSomeSlowExternalApi)`

Comment (svroonland) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:292]: It depends on what fiber the awaiting of a Promise (which is what `offset.commit` does internally) continues. I'm not sure whether it is the fiber that completes the promise or the original awaiting fiber..

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:292]: My guess would be that even though the continuation might be executed on a different fiber, it would not be executed on a different executor.

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:292]: I said that wrong. I think the continuation will continue on the same fiber and on the same executor.

Anyways, to be sure I asked [the question on Discord](https://discord.com/channels/629491597070827530/630498701860929559/1176863600040738896).

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:292]: It appears I was correct. So this is not a problem.

Comment (svroonland) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:292]: Cool! Then I have no more objections :)

**Review by svroonland — APPROVED** [review]

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 17 above)
Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:77]: @svroonland I tried to move the rebalance listener to a separate file. Unfortunately they are so integrated that it would require a lot of refactoring. I don't think it is feasible.
