### PR TITLE
Using a Consumer without consuming shouldn't throw a `RunloopTimeout` exception

### LINKED ISSUE #856: People using the Consumer to do something else than consume will experience a `RunloopTimeout`
As discussed with @erikvanoosten on discord, because we start the runloop when we instantiate the Consumer, if a user is only using the utility methods provided by the Consumer (ie. `::beginningOffsets`, `::endOffsets`, etc.), after some time, the Consumer will throw a `RunloopTimeout`.

This problem is preventing people only using these utility methods to upgrade to `v2.3+`

See the discussion starting here: https://discord.com/channels/629491597070827530/629497941719121960/1108325068284633158

### PR DESCRIPTION
**Pull request by guizmaii**
Fixes #856 

We need this PR https://github.com/zio/zio-sbt/pull/220 to merged and a new release of zio-sbt to be made to fix the CI.

The solution implemented is to boot the Runloop lazily: we only start it when the user start a consuming session

### Before:
```scala
[info] Benchmark                                        Mode  Cnt     Score    Error  Units
[info] ConsumerBenchmark.throughput                     avgt   30   205.017 ±  6.977  ms/op
[info] ConsumerBenchmark.throughputWithCommits          avgt   30   284.384 ±  8.733  ms/op
[info] ConsumersComparisonBenchmark.kafkaClients        avgt   30   647.721 ±  2.320  ms/op
[info] ConsumersComparisonBenchmark.manualKafkaClients  avgt   30   641.767 ±  2.508  ms/op
[info] ConsumersComparisonBenchmark.manualZioKafka      avgt   30  2673.759 ± 89.569  ms/op
[info] ConsumersComparisonBenchmark.zioKafka            avgt   30   737.250 ± 22.264  ms/op
```

### After:
```scala
[info] Benchmark                                        Mode  Cnt     Score     Error  Units
[info] ConsumerBenchmark.throughput                     avgt   30   209.078 ±   9.219  ms/op
[info] ConsumerBenchmark.throughputWithCommits          avgt   30   284.131 ±   9.911  ms/op
[info] ConsumersComparisonBenchmark.kafkaClients        avgt   30   645.890 ±   3.103  ms/op
[info] ConsumersComparisonBenchmark.manualKafkaClients  avgt   30   642.727 ±   2.079  ms/op
[info] ConsumersComparisonBenchmark.manualZioKafka      avgt   30  1686.490 ± 219.173  ms/op
[info] ConsumersComparisonBenchmark.zioKafka            avgt   30   722.776 ±  38.728  ms/op
```
### Conclusions

Interestingly and unexpectedly it's making the manual consumption with zio-kafka kind of way faster 🤔

Here are the details about these changes in `manualZioKafka`:
Before:
```scala
sbt:zio-kafka> zioKafkaBench/Jmh/run -wi 10 -i 10 -r 1 -w 1 -t 1 -f 5 -foe true .*ConsumersComparisonBenchmark.manualZioKafka*
...
[info] Result "zio.kafka.bench.ConsumersComparisonBenchmark.manualZioKafka":
[info]   2655.102 ±(99.9%) 99.652 ms/op [Average]
[info]   (min, avg, max) = (1634.785, 2655.102, 2810.666), stdev = 201.302
[info]   CI (99.9%): [2555.450, 2754.754] (assumes normal distribution)
[info] # Run complete. Total time: 00:08:12
```

After:
```scala
sbt:zio-kafka> zioKafkaBench/Jmh/run -wi 10 -i 10 -r 1 -w 1 -t 1 -f 5 -foe true .*ConsumersComparisonBenchmark.manualZioKafka*
...
[info] Result "zio.kafka.bench.ConsumersComparisonBenchmark.manualZioKafka":
[info]   1706.941 ±(99.9%) 214.879 ms/op [Average]
[info]   (min, avg, max) = (1084.221, 1706.941, 2791.118), stdev = 434.067
[info]   CI (99.9%): [1492.062, 1921.820] (assumes normal distribution)
[info] # Run complete. Total time: 00:07:00
```

### Before
(Results copied from #889)
```scala
zioKafkaBench/Jmh/run -wi 10 -i 10 -r 1 -w 1 -t 1 -f 3 -foe true .*comparison.*
...
[info] Result "zio.kafka.bench.comparison.KafkaClientBenchmarks.kafkaClients":
[info]   641.438 ±(99.9%) 3.349 ms/op [Average]
[info]   (min, avg, max) = (624.941, 641.438, 650.032), stdev = 5.012
[info]   CI (99.9%): [638.090, 644.787] (assumes normal distribution)
...
[info] Result "zio.kafka.bench.comparison.KafkaClientBenchmarks.manualKafkaClients":
[info]   642.514 ±(99.9%) 3.090 ms/op [Average]
[info]   (min, avg, max) = (632.069, 642.514, 656.932), stdev = 4.625
[info]   CI (99.9%): [639.424, 645.605] (assumes normal distribution)
...
[info] Result "zio.kafka.bench.comparison.ZioKafkaBenchmarks.manualZioKafka":
[info]   2605.392 ±(99.9%) 229.199 ms/op [Average]
[info]   (min, avg, max) = (1584.064, 2605.392, 2818.016), stdev = 343.055
[info]   CI (99.9%): [2376.193, 2834.592] (assumes normal distribution)
...
[info] Result "zio.kafka.bench.comparison.ZioKafkaBenchmarks.zioKafka":
[info]   734.987 ±(99.9%) 22.830 ms/op [Average]
[info]   (min, avg, max) = (683.740, 734.987, 826.528), stdev = 34.170
[info]   CI (99.9%): [712.158, 757.817] (assumes normal distribution)
...
[info] Result "zio.kafka.bench.comparison.ZioKafkaNoOptimisticResumeBenchmarks.manualZioKafka":
[info]   819.937 ±(99.9%) 120.082 ms/op [Average]
[info]   (min, avg, max) = (683.373, 819.937, 1243.105), stdev = 179.733
[info]   CI (99.9%): [699.855, 940.019] (assumes normal distribution)
...
[info] Result "zio.kafka.bench.comparison.ZioKafkaNoOptimisticResumeBenchmarks.zioKafka":
[info]   1311.588 ±(99.9%) 212.646 ms/op [Average]
[info]   (min, avg, max) = (755.915, 1311.588, 2329.325), stdev = 318.279
[info]   CI (99.9%): [1098.942, 1524.234] (assumes normal distribution)
...
[info] Benchmark                                            Mode  Cnt     Score     Error  Units
[info] KafkaClientBenchmarks.kafkaClients                   avgt   30   641.438 ±   3.349  ms/op
[info] KafkaClientBenchmarks.manualKafkaClients             avgt   30   642.514 ±   3.090  ms/op
[info] ZioKafkaBenchmarks.manualZioKafka                    avgt   30  2605.392 ± 229.199  ms/op
[info] ZioKafkaBenchmarks.zioKafka                          avgt   30   734.987 ±  22.830  ms/op
[info] ZioKafkaNoOptimisticResumeBenchmarks.manualZioKafka  avgt   30   819.937 ± 120.082  ms/op
[info] ZioKafkaNoOptimisticResumeBenchmarks.zioKafka        avgt   30  1311.588 ± 212.646  ms/op
```

### After
```scala
zioKafkaBench/Jmh/run -wi 10 -i 10 -r 1 -w 1 -t 1 -f 3 -foe true .*comparison.*
...
[info] Result "zio.kafka.bench.comparison.KafkaClientBenchmarks.kafkaClients":
[info]   645.296 ±(99.9%) 3.731 ms/op [Average]
[info]   (min, avg, max) = (629.622, 645.296, 657.384), stdev = 5.585
[info]   CI (99.9%): [641.564, 649.027] (assumes normal distribution)
...
[info] Result "zio.kafka.bench.comparison.KafkaClientBenchmarks.manualKafkaClients":
[info]   644.850 ±(99.9%) 3.046 ms/op [Average]
[info]   (min, avg, max) = (634.433, 644.850, 652.421), stdev = 4.559
[info]   CI (99.9%): [641.804, 647.896] (assumes normal distribution)
...
[info] Result "zio.kafka.bench.comparison.ZioKafkaBenchmarks.manualZioKafka":
[info]   1725.509 ±(99.9%) 283.478 ms/op [Average]
[info]   (min, avg, max) = (1083.098, 1725.509, 2688.894), stdev = 424.296
[info]   CI (99.9%): [1442.031, 2008.986] (assumes normal distribution)
...
[info] Result "zio.kafka.bench.comparison.ZioKafkaBenchmarks.zioKafka":
[info]   706.280 ±(99.9%) 23.099 ms/op [Average]
[info]   (min, avg, max) = (651.442, 706.280, 765.971), stdev = 34.573
[info]   CI (99.9%): [683.181, 729.379] (assumes normal distribution)
...
[info] Result "zio.kafka.bench.comparison.ZioKafkaNoOptimisticResumeBenchmarks.manualZioKafka":
[info]   891.336 ±(99.9%) 163.192 ms/op [Average]
[info]   (min, avg, max) = (556.650, 891.336, 1611.211), stdev = 244.258
[info]   CI (99.9%): [728.144, 1054.528] (assumes normal distribution)
...
[info] Result "zio.kafka.bench.comparison.ZioKafkaNoOptimisticResumeBenchmarks.zioKafka":
[info]   1351.880 ±(99.9%) 459.663 ms/op [Average]
[info]   (min, avg, max) = (807.197, 1351.880, 4276.599), stdev = 688.002
[info]   CI (99.9%): [892.217, 1811.544] (assumes normal distribution)
...
[info] Benchmark                                            Mode  Cnt     Score     Error  Units
[info] KafkaClientBenchmarks.kafkaClients                   avgt   30   645.296 ±   3.731  ms/op
[info] KafkaClientBenchmarks.manualKafkaClients             avgt   30   644.850 ±   3.046  ms/op
[info] ZioKafkaBenchmarks.manualZioKafka                    avgt   30  1725.509 ± 283.478  ms/op
[info] ZioKafkaBenchmarks.zioKafka                          avgt   30   706.280 ±  23.099  ms/op
[info] ZioKafkaNoOptimisticResumeBenchmarks.manualZioKafka  avgt   30   891.336 ± 163.192  ms/op
[info] ZioKafkaNoOptimisticResumeBenchmarks.zioKafka        avgt   30  1351.880 ± 459.663  ms/op
```

### Conclusions

We still see this important improvement in the  `ZioKafkaBenchmarks.manualZioKafka` benchmark. The other ones are stable.

### CODE REVIEW

File: zio-kafka/src/main/scala/zio/kafka/consumer/Consumer.scala [hunk 1]
```diff
@@ -347,39 +352,16 @@ object Consumer {
...
-                   restartStreamsOnRebalancing = settings.restartStreamOnRebalancing,
-                   runloopTimeout = settings.runloopTimeout
-                 )
-      subscriptions <- Ref.Synchronized.make(Set.empty[Subscription])
-
-      partitionAssignments <- ZStream
-                                .fromQueue(runloop.partitions)
-                                .map(_.exit)
-                                .flattenExitOption
-                                .toHub(hubCapacity)
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/Consumer.scala:380]: I managed to remove the need for this `Hub` by moving this `ZStream.fromQueue(runloop.partitions)...` creation in the `Consumer::partitionedAssignmentStream` method

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+import zio.{ Queue, RIO, Ref, Scope, Task, UIO, ZIO, ZLayer }
+
+/**
+ * This [[RunloopAccess]] is here to make the [[Runloop]] boot lazy: we only starts it when the user is starting a
+ * consuming session.
+ *
+ * This is needed because of 2 things:
+ *
+ *   1. A Consumer can be used to do something else than consuming (e.g. fetching Kafka topics metadata)
+ *   1. The [[Runloop]] has a timeout throwing a [[zio.kafka.consumer.Consumer.RunloopTimeout]] when reached. If the
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala:17]: Why 1. and then 1. again?
Because of: https://contributors.scala-lang.org/t/do-numbered-lists-actually-work-in-scaladoc-markup/2748/2?u=guizmaii

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala [hunk 3]
```diff
@@ -0,0 +1,130 @@
...
+
+  @inline def notStarted: RunloopState = NotStarted
+  @inline def stopped: RunloopState    = Stopped
+}
+
+/**
+ * This [[RunloopAccess]] is here to make the [[Runloop]] boot lazy: we only starts it when the user is starting a
+ * consuming session.
+ *
+ * // TODO Jules: DOC TO UPDATE
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala:32]: TODO @guizmaii

**Comment by erikvanoosten** [comment]
@guizmaii This is quite a sizeable refactoring. Could you guide us through the main ideas? Without those ideas it is hard to see if the implementation is correct. Some questions that pop are:

- Now that the run-loop time out is gone, when a consumer gets stuck processing, will we still stop polling from the broker?
- What is the purpose of using a Hub instead of what we had?
- There is a RunloopState.NotStarted and a RunloopState.Stopped, shall we merge them into a single state?

But please focus on the main ideas first.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala [hunk 4]
```diff
@@ -0,0 +1,128 @@
...
+    runloopStateRef.updateSomeAndGetZIO { case RunloopState.NotStarted if shouldStartIfNot => makeRunloop }
+  private def withRunloopZIO[R, A](shouldStartIfNot: Boolean)(f: Runloop => RIO[R, A]): RIO[R, A] =
+    runloop(shouldStartIfNot).flatMap {
+      case RunloopState.NotStarted       => ZIO.unit.asInstanceOf[RIO[R, A]]
+      case RunloopState.Started(runloop) => f(runloop)
+      case RunloopState.Stopped          => ZIO.unit.asInstanceOf[RIO[R, A]]
+    }
+
+  /**
+   * No need to call `Runloop::stopConsumption` if the Runloop has been stopped.
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala:53]:
```suggestion
   * No need to call `Runloop::stopConsumption` if the Runloop has not been started or has been stopped.
```

**Review by svroonland — CHANGES_REQUESTED** [review]
To be quite honest, the PR contains a lot of seemingly unnecessary (for the scope of this PR)  refactorings, rewordings of loggings and moving of code etc that make it hard to review for such a critical piece of functionality. Could you implement this functionality in-place as much as possible first and then have separate refactoring PRs?

**Comment by guizmaii** [comment]
@svroonland Done. Here's the PR where I do backported the piece of code which I was only refactoring: https://github.com/zio/zio-kafka/pull/901

I also rebase this branch on top of #901 so that this PR diff now only contains the code which is fixing #856

**Comment by erikvanoosten** [comment]
For now we need to keep the runloop timeout. We can remove it once #902 has been implemented.

File: zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala [hunk 5]
```diff
@@ -1052,11 +1059,185 @@ object ConsumerSpec extends ZIOSpecDefaultSlf4j with KafkaRandom {
...
+              // The subscription must be finalized before the runloop, otherwise it creates a deadlock.
+              equalTo(
+                Chunk(
+                  SubscriptionFinalized,
+                  RunloopFinalized,
+                  ConsumerFinalized
+                )
+              )
+            )
+          } @@ nonFlaky(5),
```
Comment (erikvanoosten) [inline zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1182]: Is this a flaky test? If so, why?

**Review by erikvanoosten — COMMENTED** [review]
Luckily, I am finally seeing the value of this PR. Thanks for that. There is a suggestion below here, I really think we can simplify RunloopAccess a lot. I will review further another time because my head needs a rest from this one 😉

File: zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala (hunk 5 above)
Comment (guizmaii) [reply zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1182]: It's testing something non-dertermistic. So we want to be sure that we didn't just get lucky

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala [hunk 6]
```diff
@@ -0,0 +1,130 @@
...
+
+  /**
+   * No need to call `Runloop::stopConsumption` if the Runloop has not been started or has been stopped.
+   *
+   * Note:
+   *   1. The `.orDie` is just here for compilation. It cannot happen.
+   *   1. We do a 100 retries waiting 10ms between each to roughly take max 1s before to stop to retry. We want to avoid
+   *      an infinite loop. We need this recursion because if the user calls `stopConsumption` before the Runloop is
+   *      started, we need to wait for it to be started. Can happen if the user starts a consuming session in a forked
+   *      fiber and immediately after forking, stops it. The Runloop will potentially not be started yet.
```
[the remark this answers is not in the document]
Comment (guizmaii) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/RunloopAccess.scala:60]: FYI @erikvanoosten I gave a try to your suggested solution here: https://github.com/zio/zio-kafka/pull/910

It seems to be working fine. The only issue I have is the `.ignore` I have to add here: https://github.com/zio/zio-kafka/pull/910/files#diff-689216f569dbe08f28a5245c0b6d35721937d800ccd3743164e2c42a4ffdb4c6R67
Either we keep this ignore or we change the `stopConsumption` return type to `Task[Unit]`.

WDYT?

**Comment by svroonland** [comment]
Ah I was hoping the PR would become significantly smaller, but it hasn't 😅  I haven't had time to review it and given the size I can't really do it in between..

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 7]
```diff
@@ -369,68 +376,107 @@ private[consumer] final class Runloop private (
...
         }
-          .tapBoth(e => cmd.fail(e), _ => cmd.succeed)
-          .uninterruptible
+      case RunloopCommand.StopSubscription => doChangeSubscription(SubscriptionState.NotSubscribed)
       case RunloopCommand.StopAllStreams =>
         for {
           _ <- ZIO.logDebug("Stop all streams initiated")
           _ <- ZIO.foreachDiscard(state.assignedStreams)(_.end())
-          _ <- partitionsQueue.offer(Take.end)
+          _ <- partitionsHub.publish(Take.end)
```
Comment (guizmaii) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:448]: Does it finalize all the Hub's subscriptions?

Comment (guizmaii) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:448]: No, it doesn't.

File: zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala [hunk 8]
```diff
@@ -1052,11 +1060,188 @@ object ConsumerSpec extends ZIOSpecDefaultSlf4j with KafkaRandom {
...
-      }
+      },
+      suite("issue #856")(
+        test(
+          "Booting a Consumer to do something else than consuming should not fail with `RunloopTimeout` exception"
+        ) {
+          def test(diagnostics: Diagnostics) =
+            for {
+              clientId <- randomClient
+              settings <- consumerSettings(clientId = clientId)
```
Comment (erikvanoosten) [inline zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1071]:
```suggestion
              settings <- consumerSettings(clientId = clientId, runloopTimeout = 1.milli)
```

File: zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala [hunk 9]
```diff
@@ -1052,11 +1060,188 @@ object ConsumerSpec extends ZIOSpecDefaultSlf4j with KafkaRandom {
...
+                                .runCount
+              } yield assert(consumed_0)(equalTo(1L)) && assert(consumed_1)(equalTo(1L))
+
+            for {
+              diagnostics <- Diagnostics.SlidingQueue.make(1000)
+              testResult <- ZIO.scoped {
+                              test(diagnostics)
+                            }
+              finalizationEvents <- diagnostics.queue.takeAll.map(_.filter(_.isInstanceOf[Finalization]))
+            } yield testResult && assert(finalizationEvents)(
```
Comment (erikvanoosten) [inline zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1130]: Just FYI, ZIO test now also supports `assert(a == b)` instead of `assert(a)(equalTo(b))`.

File: zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala [hunk 10]
```diff
@@ -1052,11 +1060,188 @@ object ConsumerSpec extends ZIOSpecDefaultSlf4j with KafkaRandom {
...
+            def test(diagnostics: Diagnostics): ZIO[Producer & Scope & Kafka, Throwable, TestResult] =
+              for {
+                clientId <- randomClient
+                topic    <- randomTopic
+                settings <- consumerSettings(clientId = clientId)
+                consumer <- Consumer.make(settings, diagnostics = diagnostics)
+                _        <- produceOne(topic, "key1", "message1")
+                // Starting a consumption session to start the Runloop.
+                consumed_0 <- consumer
+                                .plainStream(Subscription.manual(topic -> 0), Serde.string, Serde.string)
```
Comment (erikvanoosten) [inline zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1115]: This only works if we know that the topic has 1 partition. Otherwise the data might land in another partition. Shall we create the topic explicitly, just to make sure it has only 1 partition?

File: zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala (hunk 5 above)
Comment (erikvanoosten) [reply zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1186]: With this producer (you could remove the partition stuff):
```scala
  private def scheduledProducer[R](
    topic: String,
    partitionCount: Int,
    schedule: Schedule[R, Any, Long]
  ): ZStream[R with Producer, Throwable, Chunk[RecordMetadata]] =
    ZStream
      .fromSchedule(schedule)
      .mapZIO { i =>
        produceMany(topic, partition = i.toInt % partitionCount, kvs = List(s"key$i" -> s"msg$i"))
      }
```
The producer is slower and runs on its own fiber. With the correct schedule this makes it fairly impossible for the consumer to consumer everything. The test should not be flaky anymore after that. Bonus: we can abort the fiber once the consumer is done making the test a lot faster.

File: zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala (hunk 10 above)
Comment (guizmaii) [reply zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1115]: I'm sorry, I'm not sure to understand your comment. This test is testing the finalizers order. Not sure to see the relationship between your comment and the test purpose

Comment (erikvanoosten) [reply zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1115]: It only consumes from partition 0 `Subscription.manual(topic -> 0)`. If the data lands in topic 1, this consumer will see nothing.

Comment (guizmaii) [reply zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1115]: Oh ok. Well, it never happened neither in CI or locally 🤔

File: zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala (hunk 5 above)
Comment (guizmaii) [reply zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1186]: > With the correct schedule this makes it fairly impossible for the consumer to consumer everything.

The thing is that this part of the test: `assert(consumed_0)(isLessThan(numberOfMessages.toLong))` is very important. It proves that the consumption has indeed been stopped and so didn't consume everything. 
With your proposal I'm not sure to see how to prove that the consumer didn't consume everything

Comment (erikvanoosten) [reply zio-kafka-test/src/test/scala/zio/kafka/consumer/ConsumerSpec.scala:1186]: My proposal only change the producer, the rest, including that assertion, stays the same.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 11]
```diff
@@ -369,68 +376,107 @@ private[consumer] final class Runloop private (
...
-            ).map { revokeResult =>
-              newState.copy(
-                pendingRequests = revokeResult.pendingRequests,
-                assignedStreams = revokeResult.assignedStreams
-              )
+      case RunloopCommand.AddSubscription(newSubscription) =>
+        state.subscriptionState match {
+          case SubscriptionState.NotSubscribed =>
+            val newSubState =
+              SubscriptionState.Subscribed(subscriptions = Set(newSubscription), union = newSubscription)
```
Comment (erikvanoosten) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:408]: A lot of this union code could be cleaned up by moving it into another class. Let's leave that for another PR though.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 12]
```diff
@@ -369,68 +376,107 @@ private[consumer] final class Runloop private (
...
+            doChangeSubscription(newSubState)
+          case SubscriptionState.Subscribed(existingSubscriptions, _) =>
+            val subs = NonEmptyChunk.fromIterable(newSubscription, existingSubscriptions)
+
+            Subscription.unionAll(subs) match {
+              case None => ZIO.fail(InvalidSubscriptionUnion(subs))
```
Comment (erikvanoosten) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:414]: There is a problem with throwing an exception here.
Before, this failure would be returned at the place where the stream was created. Now, the failure will stop the runloop.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 13]
```diff
@@ -522,6 +565,9 @@ private[consumer] object Runloop {
     ) extends RebalanceEvent
   }
 
+  // Internal parameters, should not be necessary to tune
+  private final val commandQueueSize: Int = 1024
```
Comment (erikvanoosten) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:569]: The [naming conventions in the scala style guide](https://docs.scala-lang.org/style/naming-conventions.html#constants-values-and-variables) dictate that this should be written as:
```suggestion
  private final val CommandQueueSize: Int = 1024
```

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:569]: Not necessarily part of this PR...

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 14]
```diff
@@ -530,29 +576,23 @@ private[consumer] object Runloop {
     offsetRetrieval: OffsetRetrieval,
     userRebalanceListener: RebalanceListener,
     restartStreamsOnRebalancing: Boolean,
-    runloopTimeout: Duration,
+    partitionsHub: Hub[Take[Throwable, PartitionAssignment]],
     consumerSettings: ConsumerSettings
-  ): ZIO[Scope, Throwable, Runloop] =
+  ): URIO[Scope, Runloop] =
```
Comment (erikvanoosten) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:581]: I strongly prefer writing out the type fully. I can never remember the mnemonic aliases with R and U. Only `Task` sticks, the rest is overhead.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 12 above)
Comment (guizmaii) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:414]: Great catch! That's a shame that no tests were written to validate this behaviour. I'll write one and fix this issue.

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Pending this comment, the PR LGTM.
I will play a bit more with making RunloopAccessStates use a Promise. But that does not stop this PR.

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala]: Looks good.

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 14 above)
Comment (guizmaii) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:588]: I'd prefer it to stay like this. If you never use these type aliases you'll never get used to them. IMO, once you're familiar with them they allow us to read code faster

File: zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala [hunk 15]
```diff
@@ -45,8 +45,8 @@ trait ComparisonBenchmark extends ZioBenchmark[Env] {
         clientId = randomThing("client"),
         groupId = Some(randomThing("client")),
         `max.poll.records` = 1000, // A more production worthy value
-        runloopTimeout =
-          1.hour // Absurdly high timeout to avoid the runloop from being interrupted while we're benchmarking other stuff
+        // Absurdly high timeout to avoid the runloop from being interrupted while we're benchmarking other stuff
```
Comment (svroonland) [inline zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala:48]: Isn't this made obsolete by this PR?

File: zio-kafka/src/main/scala/zio/kafka/consumer/Consumer.scala [hunk 16]
```diff
@@ -222,43 +219,20 @@ object Consumer {
       keyDeserializer: Deserializer[R, K],
       valueDeserializer: Deserializer[R, V]
     ): Stream[Throwable, Chunk[(TopicPartition, ZStream[R, Throwable, CommittableRecord[K, V]])]] = {
-      def extendSubscriptions = subscriptions.updateZIO { existingSubscriptions =>
```
Comment (svroonland) [inline zio-kafka/src/main/scala/zio/kafka/consumer/Consumer.scala:225]: As I still find this PR quite hard to review, was it functionally necessary to move this code to the Runloop and introduce the SubscriptionState? Not that I'm against that change, but it makes this PR very large and hard to see what the actual behavioral changes are..

File: zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala (hunk 15 above)
Comment (guizmaii) [reply zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala:48]: Just to be sure, what are you talking about? About the `RunloopTimeout`?

Comment (svroonland) [reply zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala:48]: I mean, can we remove this setting override from the benchmark? I'd expect it to not cause any errors anymore because the timeout only starts when we start consuming, right?

File: zio-kafka/src/main/scala/zio/kafka/consumer/Consumer.scala (hunk 16 above)
Comment (guizmaii) [reply zio-kafka/src/main/scala/zio/kafka/consumer/Consumer.scala:225]: > was it functionally necessary to move this code to the Runloop
I'm explaining this point here: https://github.com/zio/zio-kafka/pull/857#issuecomment-1572256942

If you look attentively at the code, it's more or less just copy/pasted from the Consumer code to the Runloop.
The only change is that I need a `Promise` now to return the `InvalidSubscriptionUnion` to fail when the user creates a new consuming session with an invalid `Subscription`.
See https://github.com/zio/zio-kafka/pull/857#discussion_r1233063581

File: zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala (hunk 15 above)
Comment (guizmaii) [reply zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala:48]: > I'd expect it to not cause any errors anymore because the timeout only starts when we start consuming, right?

Yes, it does start only when we consume. 
Let me check 🤔

**Comment by guizmaii** [comment]
@erikvanoosten FYI, I remove the retry mechanism in the `RunloopAccess::stopConsumption` method. See https://github.com/zio/zio-kafka/pull/857/commits/75589412ff39a43bd187877a3966efdbf9e61110

File: zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala (hunk 15 above)
Comment (guizmaii) [reply zio-kafka-bench/src/main/scala/zio/kafka/bench/comparison/ComparisonBenchmark.scala:48]: I'd prefer to leave it like this for now. Hopefully, we'll manage to remove this global `runloopTimeout` settings

**Review by erikvanoosten — APPROVED** [review]

**Comment by guizmaii** [comment]
FYI, I renamed `RunloopState.Stopped` to `RunloopState.Finalized` to make it clearer that a Runloop can't be restarted

File: zio-kafka-test/src/test/scala/zio/kafka/consumer/SubscriptionsSpec.scala [hunk 17]
```diff
@@ -88,22 +91,94 @@ object SubscriptionsSpec extends ZIOSpecDefaultSlf4j with KafkaRandom {
...
+        group  <- randomGroup
+
+        _ <- produceMany(topic1, kvs)
+
+        counter = new AtomicInteger(1)
+
+        firstMessagesRef <- Ref.make(("", ""))
+        finalizersRef    <- Ref.make(Chunk.empty[String])
+
+        consumer_0 =
```
Comment (svroonland) [inline zio-kafka-test/src/test/scala/zio/kafka/consumer/SubscriptionsSpec.scala:131]: Can we stick to camel casing?

**Review by svroonland — APPROVED** [review]
