### PR TITLE
Remove lost partitions from assigned streams

### LINKED ISSUE #1288: Consumer doesn't consume after `onLost`
When the broker is down, the consumer loses connection to the broker, and tries to reconnect, then `onLost` happens and after that runloop will never call `poll()`, so there are no new events. Is it a desired behavior? If yes, then how to restart consumer when `onLost` happens? (Last event was consumed at 20:08). Also in the application there are two consumer groups and they read the same topic (in parallel); one fails (`onLost` happens), one continues to work (`onLost` doesn't happen, since it's connected to a broker that doesn't go down).

Related #1250. Version: **2.8.0**.

<details>
  <summary>Logs (the first message — the newest) </summary>
  
```
2024-07-19 20:10:37.441	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Offering partition assignment Set()   location: Runloop.scala:523
2024-07-19 20:10:37.438	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop.makeRebalanceListener   onLost done   location: Runloop.scala:240
2024-07-19 20:10:37.433	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.PartitionStreamControl   Partition sample-topic-3 lost   location: PartitionStreamControl.scala:98 partition: 3 topic: sample-topic
2024-07-19 20:10:37.428	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop.makeRebalanceListener   1 partitions are lost   location: Runloop.scala:234
2024-07-19 20:10:37.375	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Starting poll with 1 pending requests and 0 pending commits, resuming Set(sample-topic-3) partitions   location: Runloop.scala:466
2024-07-19 20:10:37.375	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Processing 0 commits, 1 commands: Poll   location: Runloop.scala:733
2024-07-19 20:10:37.325	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Starting poll with 1 pending requests and 0 pending commits, resuming Set(sample-topic-3) partitions   location: Runloop.scala:466
2024-07-19 20:10:37.325	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Processing 0 commits, 1 commands: Poll   location: Runloop.scala:733
2024-07-19 20:10:37.275	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Starting poll with 1 pending requests and 0 pending commits, resuming Set(sample-topic-3) partitions   location: Runloop.scala:466
2024-07-19 20:10:37.275	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Processing 0 commits, 1 commands: Poll   location: Runloop.scala:733
2024-07-19 20:10:37.225	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Starting poll with 1 pending requests and 0 pending commits, resuming Set(sample-topic-3) partitions   location: Runloop.scala:466
2024-07-19 20:10:37.225	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Processing 0 commits, 1 commands: Poll   location: Runloop.scala:733
2024-07-19 20:10:37.174	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Starting poll with 1 pending requests and 0 pending commits, resuming Set(sample-topic-3) partitions   location: Runloop.scala:466
2024-07-19 20:10:37.174	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Processing 0 commits, 1 commands: Poll   location: Runloop.scala:733
2024-07-19 20:10:37.124	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Starting poll with 1 pending requests and 0 pending commits, resuming Set(sample-topic-3) partitions   location: Runloop.scala:466
2024-07-19 20:10:37.124	zio-kafka-runloop-thread-3   zio.kafka.consumer.internal.Runloop   Processing 0 commits, 1 commands: Poll   location: Runloop.scala:733
```

</details>

### PR DESCRIPTION
**Pull request by svroonland**
Fixes #1288. See also #1233 and #1250.

When all partitions are lost after some connection issue to the broker, the streams for lost partitions are ended but polling stops, due to the conditions in `Runloop.State#shouldPoll`. This PR fixes this by removing the lost partition streams from the `assignedStreams` in the state, thereby not disabling polling. 

Also adds a warning that is logged whenever the assigned partitions (according to the apache kafka consumer) are different from the assigned streams, which helps to identify other issues or any future regressions of this issue.

~Still needs a good test, the `MockConsumer` used in other tests unfortunately does not allow simulating lost partitions, and the exact behavior of the kafka client in this situation is hard to predict..~ 
Includes a test that fails when undoing the change to Runloop

### CODE REVIEW

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala [hunk 1]
```diff
@@ -560,6 +560,17 @@ private[consumer] final class Runloop private (
...
+                                // Ensure that all assigned partitions have a stream and no streams are present for unassigned streams
+                                _ <-
+                                  ZIO
+                                    .logWarning(
+                                      s"Not all assigned partitions have a (single) stream or vice versa. Assigned: ${currentAssigned.mkString(",")}, streams: ${updatedAssignedStreams.map(_.tp).mkString(",")}"
+                                    )
+                                    .when(
+                                      currentAssigned != updatedAssignedStreams
+                                        .map(_.tp)
+                                        .toSet || currentAssigned.size != updatedAssignedStreams.size
```
Comment (erikvanoosten) [inline zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:572]: This can be simplified to:
```suggestion
                                      currentAssigned != updatedAssignedStreams.map(_.tp).toSet
```
although we could do this as a (premature) performance optimization:
```suggestion
                                      currentAssigned.size != updatedAssignedStreams.size ||
                                         currentAssigned != updatedAssignedStreams.map(_.tp).toSet
```

**Review by erikvanoosten — APPROVED** [review]
Yes, this is very good!
I am pretty sure we had code like this in the past (minus the log statement), that it was removed when we started to fail on lost partitions, and then forgot to restore it when we no longer failed on lost partitions.

**Comment by erikvanoosten** [comment]
Let's shop this asap! 😄

File: zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala (hunk 1 above)
Comment (svroonland) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:572]: I wanted to make sure that there are no duplicate TPs in `assignedStreams`, hence the size check as well. Also the size check is probably faster as the first condition to check.

Comment (erikvanoosten) [reply zio-kafka/src/main/scala/zio/kafka/consumer/internal/Runloop.scala:572]: Of course, you are right, `updatedAssignedStreams` is not a set! 👍

**Review by erikvanoosten — APPROVED** [review]
